server:
    port: 8089
spring:
    datasource:
        analysis:
            username: user
            password: password
            jdbc-url: jdbc:mysql://mysql.example.com/Analysis?allowMultiQueries=true&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
            driver-class-name: com.mysql.cj.jdbc.Driver
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: Asia/Shanghai
env:
    tmpDir: tmp
    mavenHome: /path/to/maven
    mavenSettings: /path/to/settings.xml
    javaHome: /path/to/java_home
logging:
    level:
        root: info
