server:
    port: 8089
spring:
    datasource:
        analysis:
            username: your_username
            password: your_password
            jdbc-url: jdbc:mysql://www.example.com:3306/Analysis?allowMultiQueries=true&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
            driver-class-name: com.mysql.cj.jdbc.Driver
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: Asia/Shanghai
env:
    tmpDir: tmp
    mavenHome: /usr/local/apache-maven-3.9.2
    mavenSettings: /Users/xiaoandi/.m2/settings.xml
    javaHome: /Library/Java/JavaVirtualMachines/jdk1.8.0_351.jdk/Contents/Home
